// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "../ui.h"

void ui_ScreenEditRGB_screen_init(void)
{
    ui_ScreenEditRGB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEditRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenEditRGB, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenEditRGB, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenEditRGB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenEditRGB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenEditRGB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenEditRGB, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenEditRGB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRed = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelRed, lv_pct(100));
    lv_obj_set_height(ui_PanelRed, lv_pct(25));
    lv_obj_set_x(ui_PanelRed, 5);
    lv_obj_set_y(ui_PanelRed, 0);
    lv_obj_set_align(ui_PanelRed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelRed, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelRed, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelRed, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelRed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelRed, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelRed, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblRed = lv_label_create(ui_PanelRed);
    lv_obj_set_width(ui_valueLblRed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblRed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblRed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblRed, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblRed, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblRed, "Red: ");

    ui_valueRed = lv_label_create(ui_PanelRed);
    lv_obj_set_width(ui_valueRed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueRed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueRed, 117);
    lv_obj_set_y(ui_valueRed, -33);
    lv_obj_set_align(ui_valueRed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueRed, "60");
    lv_label_set_recolor(ui_valueRed, "true");

    ui_PanelGreen = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelGreen, lv_pct(100));
    lv_obj_set_height(ui_PanelGreen, lv_pct(25));
    lv_obj_set_align(ui_PanelGreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelGreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelGreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelGreen, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelGreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelGreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelGreen, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelGreen, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblGreen = lv_label_create(ui_PanelGreen);
    lv_obj_set_width(ui_valueLblGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblGreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblGreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblGreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblGreen, "Green: ");

    ui_valueGreen = lv_label_create(ui_PanelGreen);
    lv_obj_set_width(ui_valueGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueGreen, 117);
    lv_obj_set_y(ui_valueGreen, -33);
    lv_obj_set_align(ui_valueGreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueGreen, "10");
    lv_label_set_recolor(ui_valueGreen, "true");

    ui_PanelBlue = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelBlue, lv_pct(100));
    lv_obj_set_height(ui_PanelBlue, lv_pct(25));
    lv_obj_set_align(ui_PanelBlue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelBlue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelBlue, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelBlue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBlue, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBlue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBlue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelBlue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelBlue, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblBlue = lv_label_create(ui_PanelBlue);
    lv_obj_set_width(ui_valueLblBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblBlue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblBlue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblBlue, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblBlue, "Blue: ");

    ui_valueBlue = lv_label_create(ui_PanelBlue);
    lv_obj_set_width(ui_valueBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueBlue, 117);
    lv_obj_set_y(ui_valueBlue, -33);
    lv_obj_set_align(ui_valueBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueBlue, "true");
    lv_label_set_recolor(ui_valueBlue, "true");

    ui_PanelButtons = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelButtons, lv_pct(100));
    lv_obj_set_height(ui_PanelButtons, lv_pct(25));
    lv_obj_set_align(ui_PanelButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelButtons, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelButtons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelButtons, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelButtons, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ButtonOK = lv_btn_create(ui_PanelButtons);
    lv_obj_set_width(ui_ButtonOK, 40);
    lv_obj_set_height(ui_ButtonOK, 16);
    lv_obj_set_align(ui_ButtonOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOK, lv_color_hex(0xE9A047), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonOK, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblOK = lv_label_create(ui_ButtonOK);
    lv_obj_set_width(ui_valueLblOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblOK, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblOK, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblOK, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblOK, "OK");

    ui_ButtonWHITE = lv_btn_create(ui_PanelButtons);
    lv_obj_set_width(ui_ButtonWHITE, 80);
    lv_obj_set_height(ui_ButtonWHITE, 16);
    lv_obj_set_align(ui_ButtonWHITE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonWHITE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWHITE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonWHITE, lv_color_hex(0xE9A047), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonWHITE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblWHITE = lv_label_create(ui_ButtonWHITE);
    lv_obj_set_width(ui_valueLblWHITE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblWHITE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblWHITE, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblWHITE, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblWHITE, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblWHITE, "WHITE");

}
