// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_Counter;

// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
lv_obj_t * ui_ScreenSetup;
lv_obj_t * ui_PanelEdit;
lv_obj_t * ui_itemLblEdit;
lv_obj_t * ui_Image1;
lv_obj_t * ui_PanelOptions;
lv_obj_t * ui_itemLblOptions;
lv_obj_t * ui_Image2;
lv_obj_t * ui_PanelEditRGB;
lv_obj_t * ui_itemLblRGB;
lv_obj_t * ui_Image3;
lv_obj_t * ui_PanelButtonSave;
lv_obj_t * ui_ButtonSave;
lv_obj_t * ui_valueLblSave;

// SCREEN: ui_ScreenEdit
void ui_ScreenEdit_screen_init(void);
lv_obj_t * ui_ScreenEdit;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_valueLbl1;
lv_obj_t * ui_value1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_valueLbl2;
lv_obj_t * ui_value2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_valueLbl3;
lv_obj_t * ui_value3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_valueLbl4;
lv_obj_t * ui_value4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_valueLbl5;
lv_obj_t * ui_value5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_valueLbl6;
lv_obj_t * ui_value6;

// SCREEN: ui_ScreenOptions
void ui_ScreenOptions_screen_init(void);
lv_obj_t * ui_ScreenOptions;
lv_obj_t * ui_PanelEditHID;
lv_obj_t * ui_CheckboxHID;
lv_obj_t * ui_PanelEditMount;
lv_obj_t * ui_CheckboxMount;

// SCREEN: ui_ScreenEditRGB
void ui_ScreenEditRGB_screen_init(void);
lv_obj_t * ui_ScreenEditRGB;
lv_obj_t * ui_PanelRed;
lv_obj_t * ui_valueLblRed;
lv_obj_t * ui_valueRed;
lv_obj_t * ui_PanelGreen;
lv_obj_t * ui_valueLblGreen;
lv_obj_t * ui_valueGreen;
lv_obj_t * ui_PanelBlue;
lv_obj_t * ui_valueLblBlue;
lv_obj_t * ui_valueBlue;
lv_obj_t * ui_PanelButtons;
lv_obj_t * ui_ButtonOK;
lv_obj_t * ui_valueLblOK;
lv_obj_t * ui_ButtonWHITE;
lv_obj_t * ui_valueLblWHITE;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_155062242[1] = {&ui_img_749525677};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMain_screen_init();
    ui_ScreenSetup_screen_init();
    ui_ScreenEdit_screen_init();
    ui_ScreenOptions_screen_init();
    ui_ScreenEditRGB_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMain);
}
