// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "../ui.h"

void ui_ScreenEdit_screen_init(void)
{
    ui_ScreenEdit = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_ScreenEdit, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenEdit, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenEdit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel1, lv_pct(92));
    lv_obj_set_height(ui_Panel1, lv_pct(24));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_valueLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl1, "Value 1: ");

    ui_value1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value1, 117);
    lv_obj_set_y(ui_value1, -33);
    lv_obj_set_align(ui_value1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value1, "150");
    lv_label_set_recolor(ui_value1, "true");

    ui_Panel2 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel2, lv_pct(92));
    lv_obj_set_height(ui_Panel2, lv_pct(24));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_valueLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl2, "Value 2: ");

    ui_value2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_value2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value2, 117);
    lv_obj_set_y(ui_value2, -33);
    lv_obj_set_align(ui_value2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value2, "1500");
    lv_label_set_recolor(ui_value2, "true");

    ui_Panel3 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel3, lv_pct(92));
    lv_obj_set_height(ui_Panel3, lv_pct(24));
    lv_obj_set_x(ui_Panel3, 5);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_valueLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl3, "Value 3: ");

    ui_value3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_value3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value3, 117);
    lv_obj_set_y(ui_value3, -33);
    lv_obj_set_align(ui_value3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value3, "36.5");
    lv_label_set_recolor(ui_value3, "true");

    ui_Panel4 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel4, lv_pct(92));
    lv_obj_set_height(ui_Panel4, lv_pct(24));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_valueLbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl4, "Value 4: ");

    ui_value4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_value4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value4, 117);
    lv_obj_set_y(ui_value4, -33);
    lv_obj_set_align(ui_value4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value4, "25.63");
    lv_label_set_recolor(ui_value4, "true");

    ui_Panel5 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel5, lv_pct(92));
    lv_obj_set_height(ui_Panel5, lv_pct(24));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_valueLbl5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl5, "Value 5: ");

    ui_value5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_value5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value5, 117);
    lv_obj_set_y(ui_value5, -33);
    lv_obj_set_align(ui_value5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value5, "true");
    lv_label_set_recolor(ui_value5, "true");

    ui_Panel6 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel6, lv_pct(92));
    lv_obj_set_height(ui_Panel6, lv_pct(24));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_valueLbl6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueLbl6, 0);
    lv_obj_set_y(ui_valueLbl6, -1);
    lv_obj_set_align(ui_valueLbl6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl6, "Value 6: ");

    ui_value6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_value6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value6, 117);
    lv_obj_set_y(ui_value6, -33);
    lv_obj_set_align(ui_value6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value6, "true");
    lv_label_set_recolor(ui_value6, "true");

}
