// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "../ui.h"

void ui_ScreenSetup_screen_init(void)
{
    ui_ScreenSetup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenSetup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenSetup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenSetup, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEdit = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelEdit, lv_pct(100));
    lv_obj_set_height(ui_PanelEdit, lv_pct(22));
    lv_obj_set_align(ui_PanelEdit, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEdit, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEdit, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEdit, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEdit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEdit, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEdit, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblEdit = lv_label_create(ui_PanelEdit);
    lv_obj_set_width(ui_itemLblEdit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblEdit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblEdit, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_itemLblEdit, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_itemLblEdit, "Edit Variables");
    lv_obj_set_style_border_color(ui_itemLblEdit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblEdit, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblEdit, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image1 = lv_img_create(ui_PanelEdit);
    lv_img_set_src(ui_Image1, &ui_img_749525677);
    lv_obj_set_width(ui_Image1, 16);
    lv_obj_set_height(ui_Image1, 16);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelOptions = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelOptions, lv_pct(100));
    lv_obj_set_height(ui_PanelOptions, lv_pct(22));
    lv_obj_set_align(ui_PanelOptions, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelOptions, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelOptions, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelOptions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelOptions, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelOptions, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelOptions, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelOptions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelOptions, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelOptions, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblOptions = lv_label_create(ui_PanelOptions);
    lv_obj_set_width(ui_itemLblOptions, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblOptions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblOptions, LV_ALIGN_CENTER);
    lv_label_set_text(ui_itemLblOptions, "App Options");
    lv_obj_set_style_border_color(ui_itemLblOptions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblOptions, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblOptions, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image2 = lv_img_create(ui_PanelOptions);
    lv_img_set_src(ui_Image2, &ui_img_749525677);
    lv_obj_set_width(ui_Image2, 16);
    lv_obj_set_height(ui_Image2, 16);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelEditRGB = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelEditRGB, lv_pct(100));
    lv_obj_set_height(ui_PanelEditRGB, lv_pct(22));
    lv_obj_set_align(ui_PanelEditRGB, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEditRGB, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEditRGB, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEditRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEditRGB, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEditRGB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEditRGB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEditRGB, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblRGB = lv_label_create(ui_PanelEditRGB);
    lv_obj_set_width(ui_itemLblRGB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblRGB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblRGB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_itemLblRGB, "RGB Led ");
    lv_obj_set_style_border_color(ui_itemLblRGB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblRGB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblRGB, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image3 = lv_img_create(ui_PanelEditRGB);
    lv_img_set_src(ui_Image3, &ui_img_749525677);
    lv_obj_set_width(ui_Image3, 16);
    lv_obj_set_height(ui_Image3, 16);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelButtonSave = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelButtonSave, lv_pct(100));
    lv_obj_set_height(ui_PanelButtonSave, lv_pct(22));
    lv_obj_set_align(ui_PanelButtonSave, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelButtonSave, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelButtonSave, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButtonSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelButtonSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelButtonSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelButtonSave, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelButtonSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelButtonSave, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelButtonSave, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ButtonSave = lv_btn_create(ui_PanelButtonSave);
    lv_obj_set_height(ui_ButtonSave, 16);
    lv_obj_set_width(ui_ButtonSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_ButtonSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSave, lv_color_hex(0xE9A047), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonSave, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblSave = lv_label_create(ui_ButtonSave);
    lv_obj_set_width(ui_valueLblSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblSave, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblSave, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblSave, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblSave, "Save to file");

}
