// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Counter = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Counter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Counter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Counter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Counter, "0");
    lv_obj_set_style_text_font(ui_Counter, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

}
